name: 'GitHubActions'

on: [push]

jobs:
  test-failure: 
    name: 'Test Failure'
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    steps:
    - name: Exit 1
      continue-on-error: true
      run: exit 1

    - name: Next Step
      run: echo "next step"
    
    - name: GITHUB_RUN_NUMBER
      run: echo $GITHUB_RUN_NUMBER
